### ISSUE TITLE
关于论文中 Speaker-Aware Disentanglement Strategy 的一些疑惑

### ISSUE THREAD

**Issue by MaoGWLeon** [JasonForJoy/SA-BERT#7]
作者您好，我想问下论文中介绍的 Speaker-Aware Disentanglement Strategy 具体体现在哪些代码里面吗？

**Comment by JasonForJoy** [comment]
@MaoGWLeon 
你好。该repo下的代码与模型是基于Ubuntu V1。
如我们论文中所述，有四个数据集已经被数据集发布者提前解纠缠好。
Speaker-Aware Disentanglement Strategy只用在我们论文中DSTC8这个数据集上。
如有需要，可以留下邮箱，我将部分处理代码邮件发送。
祝好。

**Comment by MaoGWLeon** [comment]
我的邮箱是292213785@qq.com，非常感谢您的回复。

**Comment by JasonForJoy** [comment]
@MaoGWLeon 
已发，请查收。

**Comment by MaoGWLeon** [comment]
@JasonForJoy 已收到，非常感谢👍

**Comment by o-github-o** [comment]
> @MaoGWLeon 已发，请查收。
请问这部分代码现在还有吗，想看一下：zhourenq123@163.com
