### ISSUE TITLE
請問可以公開其他的資料集嗎

### ISSUE THREAD

**Issue by WenTingTseng** [JasonForJoy/SA-BERT#8]
你好:
我想請問是否能公開其他的資料集嗎
或是有資料量較小的資料集嗎

謝謝

**Comment by JasonForJoy** [comment]
@WenTingTseng 
你好!
我们论文中用到的所有数据集都已公开可供下载，具体可见： https://github.com/JasonForJoy/IMN#datasets
祝好。

**Comment by WenTingTseng** [comment]
了解，感謝您的回覆
另外，我想請問train.py裡面有使用到GPU嗎?
有的話是在那裡使用到
因為我在訓練的時候似乎沒有吃到GPU

謝謝

**Comment by JasonForJoy** [comment]
指定GPU在 scripts/ubuntu_train.sh

**Comment by WenTingTseng** [comment]
在scripts/ubuntu_train.sh裡面指定就好了嗎?
程式碼裡面不用再設定引用嗎?
我在run scripts/ubuntu_train.sh的時候有加CUDA_VISIBLE_DEVICES=0
但是nvidia-smi查看的時候確實都沒有用到而且一直卡在
`INFO:tensorflow:Epoch 0 training begin`都沒有動靜 ...

**Comment by JasonForJoy** [comment]
只需在scripts/ubuntu_train.sh里面指定即可。
你可以检查一下是否安装的是tensorflow-gpu版本。
有可能你装的是tensorflow-cpu版本，才会计算非常慢卡着没有动静，同时nvidia-smi查看不到GPU使用进程。

**Comment by WenTingTseng** [comment]
謝謝你的幫忙，的確是用到tensorflow-cpu版本了，改成tensorflow-gpu版本就快多了
有問題再請教你，謝謝喔
